### PR TITLE
Added more robust test case for pvacseq wrapper

### PR DESCRIPTION
**Pull request by agraubert**
I built a better test for the pvacseq main pipeline.  Since travis can't run NetMHC, the test will simply copy in a pre-made .xls file (from our testing data) to trick pvacseq into thinking NetMHC produced output.  The pipeline runs all the way from start to finish, and the test checks the output produced by each stage.

I think this PR should remain open until #51 is finalized and merged, and I'll update the test and test data at that point.

### CODE REVIEW

**Comment by chrisamiller** [comment]
+1

**Comment by agraubert** [comment]
Once #56 is merged, I'll rebase this back onto python and fix up the conflicts

**Comment by agraubert** [comment]
Okay.  I'm updating the binding filter to handle the new tsv format

**Comment by agraubert** [comment]
Once #58 is merged, this build should be pass

**Comment by agraubert** [comment]
Okay, this is mostly fixed up now.  Once #62 is merged, that will fix the last issue which is breaking this pr

**Comment by susannasiebert** [comment]
#63 and #64 will probably also require changes to this test but it doesn't matter to me which ones gets merged first.

**Comment by agraubert** [comment]
I guess whichever happens first.  I'll keep updating this branch as needed for pr's getting merged ahead of it

**Comment by agraubert** [comment]
Any sense in pushing the updated ref as I change it, considering the tests are still broken?

**Pull request merged**
