### PR TITLE
Wait 60 seconds between requests to the IEDB API

### PR DESCRIPTION
**Pull request by susannasiebert**
Unfortunately, this change also affects the pvacseq.py test. Ideas on how to circumvent this are very welcome.

### CODE REVIEW

**Comment by chrisamiller** [comment]
+1
The obvious way seems to be set kind of testing flag that causes the shorter time to be used. (parameter? environment variable?)

**Comment by susannasiebert** [comment]
If we make this a parameter then any user can change that number. I'm not sure if that is desirable or not. I guess it's a bit of a "use at your own risk" sort of thing. With an environment variable for testing the user could still turn it on to circumvent the system but they would need to find out what the variable is called first.

**Comment by tmooney** [comment]
Yeah--it doesn't necessarily need to be exposed as a command-line option.  Someone who's determined could edit the code, anyway :smile:

**Comment by susannasiebert** [comment]
I added an environment flag to turn the wait off for testing.

**Comment by tmooney** [comment]
Maybe a silly question, but should there be at least one test that exercises the waiting code?

**Comment by susannasiebert** [comment]
Hm, maybe? Probably? Let me think about how to best accomplish that.

**Comment by susannasiebert** [comment]
The integration tests are currently failing because of the typo addressed in #276.

**Comment by susannasiebert** [comment]
@tmooney I added a test to test the waiting code.

**Pull request merged**
