### PR TITLE
Changed supprocess.call to use shell=False for in tests

### PR DESCRIPTION
**Pull request by agraubert**

### CODE REVIEW

**Comment by susannasiebert** [comment]
+1

**Comment by acoffman** [comment]
My only question here is in regards to cleanup. Now that any of these shell commands could throw an exception and potentially terminate the program, do we need to handle those exceptions and cleanup temporary or bogus files somehow?

Assuming we're taking care of that in some manner, +1 🎉

**Comment by agraubert** [comment]
The tests will automatically clean up any files they made regardless of if the test passed or failed (although they will issue warnings if temporary directories end up getting closed implicitly when the interpreter exits).  

In main.py, there is a call to `split` which could fail, and would halt the program.  (valid) output from the upstream parts of the program would still be present in the output directory.  main.py has `split` place files inside of another temporary directory, so any files which were produced by `split` before it crashed would be cleaned when the interpreter exits anyways.  Besides that, this call to `split` is removed in #97

**Comment by acoffman** [comment]
Cool, sounds good to me!

+1

**Pull request merged**
