### PR TITLE
Write intermediate files to a tmp directory under main output directory

### PR DESCRIPTION
**Pull request by susannasiebert**
I chose to create this `tmp` directory under the main output directory instead of using the `tempfile` module so that the solution will be compatible with #112. Otherwise the directory would get deleted when the run exists.

### CODE REVIEW

**Comment by agraubert** [comment]
+1

**Comment by jasonwalker80** [comment]
+1, but I'd suggest a new command-line option to remove 'tmp' once the pipeline has successfully run.

**Comment by susannasiebert** [comment]
I pushed a new commit with an option to keep temporary files (and delete the tmp directory if it's not set)

**Comment by jasonwalker80** [comment]
+1

**Pull request merged**
