### PR TITLE
Add Wildtype VEP plugin 

### PR DESCRIPTION
**Pull request by susannasiebert**
This is one of the VEP plugins that the user will need to use when annotating their VCFs with VEP.

Part of #41.

### CODE REVIEW

**Comment by chrisamiller** [comment]
+1

**Comment by agraubert** [comment]
When I try to run this, I get an error that it couldn't locate "Bio/EnsEMBL/Variation/Utils/BaseVepPlugin.pm"
Is that because I don't have VEP installed already?

**Comment by susannasiebert** [comment]
@graubert. Maybe I'm misunderstanding, but you wouldn't run this plugin directly but instead copy it into a directory with all the other VEP plugins. Or did you get this error when running the command to copy the plugin? Could you give some more details on what command you ran when receiving this error?

**Comment by agraubert** [comment]
I honestly have no idea what the problem was.  I'm not getting the error anymore.  I was probably just running it wrong/doing things wrong in general.  Anyways...

**Comment by agraubert** [comment]
+1

**Comment by susannasiebert** [comment]
I also changed the setup.py here so that the VEP_plugins folder would be included.

**Pull request merged**
