### PR TITLE
Converter for VCF file to annotated tsv

### LINKED ISSUE #53: Create a VCF to TSV conversion tool

### PR DESCRIPTION
**Pull request by susannasiebert**
Closes #53

### CODE REVIEW

**Comment by agraubert** [comment]
Is the current plan to only allow VCFs as input, or to allow VCF or TSV input (and perform the additional VCF->TSV step when necessary)?  I only ask because I'm curious how we want this converter built into the command structure and/or main.py

**Comment by chrisamiller** [comment]
1) I think VCF should be required as an input (not TSV). Let's commit to the genomic standard here.
2) I don't think VCF will be an output, just various reports, so I don't see any reason to maintain the VCF internally.

**Comment by jhundal** [comment]
While I agree with @chrisamiller, we could always provide the VCF to TSV converter for backward compatibility.

**Comment by susannasiebert** [comment]
I'm fine with making the VCF the required input. The current setup prepends this step before generate_fasta. generate_fasta and all downstream steps (filtering) rely on the tsv format. With the current setup we could potentially give the option of tsv input if users ask for that in the future. That would be an easy change since you would just skip the conversion step.

One thing that Jasreet and I weren't sure about is whether it is possible to add readcounts to a vcf. I know the variant reporting framework does this but I had a hard time figuring out exactly how when I dug into the code base. I didn't spend too much time on it, though, since I'm trying to meet a deadline.

**Comment by jhundal** [comment]
Prepends this VCF to TSV conversion step before generate_fasta is a great decision. Makes downstream stuff easier!

**Comment by chrisamiller** [comment]
Sounds fine to me.  Yes, adding readcounts to a VCF is straightforward, but I don't have a code example handy at the moment!

**Comment by susannasiebert** [comment]
When we update the binding filter to python we should consider updating the convert to expect readcounts in the vcf. And give instructions on how to annotate a vcf with readcounts. That's an optional goal for this milestone, though, I think.

**Comment by susannasiebert** [comment]
@agraubert I plan on making a separate PR for updating the wrappers. At that point I also plan on updating the example data and running the whole thing from start to finish to make sure all steps work.

**Comment by agraubert** [comment]
Perfect.  If we're not going to add this as an independent subcommand, then pvacseq.py doesn't need any changes.  It'll just be main.py, pvacseq/lib/__init__.py, and probably binding_filter.py

**Comment by susannasiebert** [comment]
Good point about the subcommand. I'm actually not sure if this converter should be a subcommand or not. @chrisamiller @jhundal thoughts?

**Comment by chrisamiller** [comment]
+1 I skimmed a few of the tests and the inputs/outputs seem to match up as expected

**Comment by agraubert** [comment]
+1

**Pull request merged**
