### PR TITLE
Handle frameshift mutations with range positions

### PR DESCRIPTION
**Pull request by susannasiebert**
This PR addresses the error in issue #123.

### CODE REVIEW

**Comment by strixeh** [comment]
If possible, it would be nice to have a example of a correctly annotated VCF that include all possible variants. For us novice people, it could be helpful.

-Nils

**Comment by susannasiebert** [comment]
Have you checked out the vcf in the example data (`pvacseq download_example_data`). Is that one sufficient or would you like it to contain every permutation of possible data?

**Comment by strixeh** [comment]
Oh, stupid of me, I didnt realize that the file contained all kind of variants. I used a vcf with only missense mutations when I tried pvacseq out and thought that was the file from you guys. I apologize.

**Comment by susannasiebert** [comment]
You might've had an old version of the example data from back when we didn't support indels. We try to keep the example data up to date with the features we add.

**Comment by agraubert** [comment]
+1

**Comment by jasonwalker80** [comment]
+1

**Pull request merged**
